[logging]
level = 3

[api]
draw_lookahead_period_count = 10
bind_private = "127.0.0.1:33034"
bind_public = "0.0.0.0:33035"
max_arguments = 128

[execution]
max_final_events = 10000
readonly_queue_length = 10
cursor_delay = 2000

[ledger]
initial_sce_ledger_path = "base_config/initial_sce_ledger.json"
disk_ledger_path = "storage/ledger/rocks_db"
final_history_length = 100

[consensus]
max_discarded_blocks = 100
future_block_processing_max_periods = 100
max_future_processing_blocks = 400
max_dependency_blocks = 2048
force_keep_final_periods = 20
max_operations_fill_attempts = 102400
operation_batch_size = 2048
ledger_path = "storage/ledger"
ledger_cache_capacity = 1048576
ledger_flush_interval = 10000
ledger_reset_at_startup = true
initial_ledger_path = "base_config/initial_ledger.json"
max_send_wait = 0
block_db_prune_interval = 5000
initial_rolls_path = "base_config/initial_rolls.json"
pos_draw_cached_cycles = 10
staking_keys_path = "config/staking_keys.json"
stats_timespan = 60000
max_item_return_count = 100

[protocol]
message_timeout = 5000
ask_block_timeout = 10000
max_node_known_blocks_size = 1024
max_node_wanted_blocks_size = 1024
max_simultaneous_ask_blocks_per_node = 128
max_send_wait = 0
max_known_ops_size = 2048
max_known_endorsements_size = 1024
operation_batch_buffer_capacity = 10024
operation_batch_proc_period = 500
asked_operations_pruning_period = 100000
max_operations_per_message = 1024

[network]
bind = "[::]:31244"
protocol_port = 31244
connect_timeout = 3000
wakeup_interval = 5000
peers_file = "storage/peers.json"
initial_peers_file = "base_config/initial_peers.json"
max_in_connections_per_ip = 5
max_idle_peers = 10000
max_banned_peers = 100
max_advertise_length = 10000
peers_file_dump_interval = 10000
max_message_size = 1048576000
message_timeout = 5000
ask_peer_list_interval = 30000
private_key_file = "config/node_privkey.key"
max_ask_blocks_per_message = 128
max_operations_per_message = 1024
max_endorsements_per_message = 1024
max_send_wait = 0
ban_timeout = 3600000
peer_list_send_timeout = 100
max_in_connection_overflow = 100

[bootstrap]
bootstrap_list = [ [ "145.239.66.206:31245", "ttLGkBa24jHaEWndd3WZw7yAeHdvLUNCEscyUChodf996WQm9",], [ "51.75.131.129:31245", "bH3nQ1w3bKRCFMqiCFQCwgDuDzJTwN5zDv2zn1ocL6gVpTmMQ",],]
bind = "[::]:31245"
connect_timeout = 15000
retry_delay = 60000
max_ping = 10000
read_timeout = 10000
write_timeout = 10000
read_error_timeout = 200
write_error_timeout = 200
enable_clock_synchronization = false
cache_duration = 15000
max_simultaneous_bootstraps = 2
ip_list_max_size = 10000
per_ip_min_interval = 1000

[pool]
max_pool_size_per_thread = 25000
max_operation_future_validity_start_periods = 100
max_endorsement_count = 10000
max_item_return_count = 100

[network.peer_types_config.Standard]
target_out_connections = 10
max_out_attempts = 10
max_in_connections = 15

[network.peer_types_config.Bootstrap]
target_out_connections = 1
max_out_attempts = 1
max_in_connections = 1

[network.peer_types_config.WhiteListed]
target_out_connections = 2
max_out_attempts = 2
max_in_connections = 3
