[package]
name = "massa_pool"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
num = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.15", features = ["full"] }
tracing = "0.1"
# custom modules
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_storage = { path = "../massa-storage" }

[dev-dependencies]
serial_test = "0.5"
lazy_static = "1.4.0"
massa_signature = { path = "../massa-signature" }
massa_hash = { path = "../massa-hash" }
futures = "0.3"
massa_time = { path = "../massa-time" }

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = ["tokio/tracing", "massa_models/instrument", "massa_protocol_exports/instrument"]
